function validateDFFOCTInputMaps(maps, expectedFrames)
% Reject ambiguous or incompatible quantitative-map units before inference.
    required = {'H_Hz', 'V_power', 'powerMode', 'frameCount', ...
        'samplingRateHz', 'bandHz', 'frameNormalize'};
    assert(isstruct(maps) && isscalar(maps) && all(isfield(maps, required)), ...
        'DFFOCT:MissingMetadata', ...
        'Missing map fields. Generate maps with the supplied preprocessing code.');
    assert(strcmpi(string(maps.powerMode), 'amplitudeSquared'), ...
        'DFFOCT:WrongPowerMode', ...
        'V must already be normalized by N^2. Legacy maps cannot be used directly.');
    assert(isscalar(maps.frameCount) && maps.frameCount == expectedFrames && ...
        isscalar(maps.samplingRateHz) && maps.samplingRateHz == 100 && ...
        isequal(double(maps.bandHz(:))', [1 50]) && ...
        isscalar(maps.frameNormalize) && logical(maps.frameNormalize), ...
        'DFFOCT:AcquisitionMismatch', ...
        'This checkpoint requires %d frames, 100 Hz, V band 1-50 Hz, and frame normalization.', ...
        expectedFrames);
    assert(isnumeric(maps.H_Hz) && isnumeric(maps.V_power) && ...
        isreal(maps.H_Hz) && isreal(maps.V_power) && ...
        ismatrix(maps.H_Hz) && ~isempty(maps.H_Hz) && ...
        isequal(size(maps.H_Hz), size(maps.V_power)), ...
        'DFFOCT:InvalidMapShape', 'H_Hz and V_power must be equally sized real 2-D maps.');
    assert(~any(maps.V_power < 0, 'all'), ...
        'DFFOCT:NegativePower', 'V_power cannot contain negative values.');
    if isfield(maps, 'validMask')
        assert(isequal(size(maps.validMask), size(maps.H_Hz)), ...
            'DFFOCT:InvalidMaskShape', 'validMask must have the same size as H_Hz.');
    end
end
